FROM node:12-slim
LABEL maintainer="Gem Huang <gemhuang@iii.org.tw>"

# Install pm2
RUN npm install pm2 serve -g

# Expose ports needed to use Keymetrics.io
EXPOSE 3000

COPY . /app

WORKDIR /app

RUN npm install && npm run build

# Start pm2.json process file
CMD ["pm2-runtime", "start", "pm2.json"]
# pm2 start my-app/node_modules/react-scripts/scripts/start.js --name "my-app"
# CMD ["pm2", "start", "node_modules/react-scripts/scripts/start.js", "--name", "dti-template"]
# CMD ["pm2", "serve", "build", "3000", "--spa"]
